---
- name: Install MariaDB
  yum:
    name: "{{ item }}"
    state: present
  with_items:
     - "mariadb"
     - "mariadb-server"
- name: Install MySQLDB python package for secure installations.
  yum:
    name: MySQL-python
    state: present
 # when: mysql_secure_installation and mysql_root_password is defined
